// Ported from cc-switch src-tauri/src/database/schema.rs
// Prices are per 1M tokens. Foreign model prices are USD; domestic model prices are CNY.

export const DEFAULT_PRICING = {
    // === Claude Models ===
    'claude-opus-4-7': { displayName: 'Claude Opus 4.7', input: 5, output: 25, cacheRead: 0.50, cacheWrite: 6.25 },
    'claude-opus-4-6-20260206': { displayName: 'Claude Opus 4.6', input: 5, output: 25, cacheRead: 0.50, cacheWrite: 6.25 },
    'claude-sonnet-4-6-20260217': { displayName: 'Claude Sonnet 4.6', input: 3, output: 15, cacheRead: 0.30, cacheWrite: 3.75 },
    'claude-opus-4-5-20251101': { displayName: 'Claude Opus 4.5', input: 5, output: 25, cacheRead: 0.50, cacheWrite: 6.25 },
    'claude-sonnet-4-5-20250929': { displayName: 'Claude Sonnet 4.5', input: 3, output: 15, cacheRead: 0.30, cacheWrite: 3.75 },
    'claude-haiku-4-5-20251001': { displayName: 'Claude Haiku 4.5', input: 1, output: 5, cacheRead: 0.10, cacheWrite: 1.25 },
    'claude-opus-4-20250514': { displayName: 'Claude Opus 4', input: 15, output: 75, cacheRead: 1.50, cacheWrite: 18.75 },
    'claude-opus-4-1-20250805': { displayName: 'Claude Opus 4.1', input: 15, output: 75, cacheRead: 1.50, cacheWrite: 18.75 },
    'claude-sonnet-4-20250514': { displayName: 'Claude Sonnet 4', input: 3, output: 15, cacheRead: 0.30, cacheWrite: 3.75 },
    'claude-mythos-5': { displayName: 'Claude Mythos 5', input: 10, output: 50, cacheRead: 1.00, cacheWrite: 12.50 },

    // === GPT-5.x Series ===
    'gpt-5.6-sol': { displayName: 'GPT-5.6 Sol', input: 5, output: 30, cacheRead: 0.50, cacheWrite: 6.25 },
    'gpt-5.6-terra': { displayName: 'GPT-5.6 Terra', input: 2.50, output: 15, cacheRead: 0.25, cacheWrite: 3.125 },
    'gpt-5.6-luna': { displayName: 'GPT-5.6 Luna', input: 1, output: 6, cacheRead: 0.10, cacheWrite: 1.25 },
    'gpt-5.5': { displayName: 'GPT-5.5', input: 5, output: 30, cacheRead: 0.50, cacheWrite: 0 },
    'gpt-5.5-low': { displayName: 'GPT-5.5 Low', input: 5, output: 30, cacheRead: 0.50, cacheWrite: 0 },
    'gpt-5.5-medium': { displayName: 'GPT-5.5 Medium', input: 5, output: 30, cacheRead: 0.50, cacheWrite: 0 },
    'gpt-5.5-high': { displayName: 'GPT-5.5 High', input: 5, output: 30, cacheRead: 0.50, cacheWrite: 0 },
    'gpt-5.5-xhigh': { displayName: 'GPT-5.5 XHigh', input: 5, output: 30, cacheRead: 0.50, cacheWrite: 0 },
    'gpt-5.5-minimal': { displayName: 'GPT-5.5 Minimal', input: 5, output: 30, cacheRead: 0.50, cacheWrite: 0 },
    'gpt-5.4': { displayName: 'GPT-5.4', input: 2.50, output: 15, cacheRead: 0.25, cacheWrite: 0 },
    'gpt-5.4-mini': { displayName: 'GPT-5.4 Mini', input: 0.75, output: 4.50, cacheRead: 0.075, cacheWrite: 0 },
    'gpt-5.4-nano': { displayName: 'GPT-5.4 Nano', input: 0.20, output: 1.25, cacheRead: 0.02, cacheWrite: 0 },
    'gpt-5.2': { displayName: 'GPT-5.2', input: 1.75, output: 14, cacheRead: 0.175, cacheWrite: 0 },
    'gpt-5.2-codex': { displayName: 'GPT-5.2 Codex', input: 1.75, output: 14, cacheRead: 0.175, cacheWrite: 0 },
    'gpt-5.3-codex': { displayName: 'GPT-5.3 Codex', input: 1.75, output: 14, cacheRead: 0.175, cacheWrite: 0 },
    'gpt-5.1': { displayName: 'GPT-5.1', input: 1.25, output: 10, cacheRead: 0.125, cacheWrite: 0 },
    'gpt-5.1-codex': { displayName: 'GPT-5.1 Codex', input: 1.25, output: 10, cacheRead: 0.125, cacheWrite: 0 },
    'gpt-5': { displayName: 'GPT-5', input: 1.25, output: 10, cacheRead: 0.125, cacheWrite: 0 },
    'gpt-5-codex': { displayName: 'GPT-5 Codex', input: 1.25, output: 10, cacheRead: 0.125, cacheWrite: 0 },
    'gpt-5-chat': { displayName: 'GPT-5 Chat', input: 1.25, output: 10, cacheRead: 0.125, cacheWrite: 0 },
    'gpt-5-mini': { displayName: 'GPT-5 Mini', input: 0.25, output: 2, cacheRead: 0.025, cacheWrite: 0 },
    'gpt-5-nano': { displayName: 'GPT-5 Nano', input: 0.05, output: 0.40, cacheRead: 0.005, cacheWrite: 0 },

    // === OpenAI Reasoning ===
    'o3': { displayName: 'OpenAI o3', input: 2, output: 8, cacheRead: 0.50, cacheWrite: 0 },
    'o3-pro': { displayName: 'OpenAI o3-pro', input: 20, output: 80, cacheRead: 0, cacheWrite: 0 },
    'o3-mini': { displayName: 'OpenAI o3-mini', input: 0.55, output: 2.20, cacheRead: 0.55, cacheWrite: 0 },
    'o3-deep-research': { displayName: 'OpenAI o3 Deep Research', input: 10, output: 40, cacheRead: 2.50, cacheWrite: 0 },
    'o4-mini': { displayName: 'OpenAI o4-mini', input: 1.10, output: 4.40, cacheRead: 0.275, cacheWrite: 0 },
    'o4-mini-deep-research': { displayName: 'OpenAI o4-mini Deep Research', input: 2, output: 8, cacheRead: 0.50, cacheWrite: 0 },
    'o1': { displayName: 'OpenAI o1', input: 15, output: 60, cacheRead: 7.50, cacheWrite: 0 },
    'o1-mini': { displayName: 'OpenAI o1-mini', input: 0.55, output: 2.20, cacheRead: 0.55, cacheWrite: 0 },
    'o1-preview': { displayName: 'OpenAI o1 Preview', input: 15, output: 60, cacheRead: 7.50, cacheWrite: 0 },

    // === GPT-4.1 ===
    'gpt-4.1': { displayName: 'GPT-4.1', input: 2, output: 8, cacheRead: 0.50, cacheWrite: 0 },
    'gpt-4.1-mini': { displayName: 'GPT-4.1 Mini', input: 0.40, output: 1.60, cacheRead: 0.10, cacheWrite: 0 },
    'gpt-4.1-nano': { displayName: 'GPT-4.1 Nano', input: 0.10, output: 0.40, cacheRead: 0.025, cacheWrite: 0 },
    'codex-mini': { displayName: 'Codex Mini', input: 0.75, output: 3, cacheRead: 0.025, cacheWrite: 0 },
    'gpt-4.5-preview': { displayName: 'GPT-4.5 Preview', input: 75, output: 150, cacheRead: 37.50, cacheWrite: 0 },
    'gpt-4o': { displayName: 'GPT-4o', input: 2.50, output: 10, cacheRead: 1.25, cacheWrite: 0 },
    'gpt-4o-mini': { displayName: 'GPT-4o Mini', input: 0.15, output: 0.60, cacheRead: 0.075, cacheWrite: 0 },
    'gpt-4-turbo': { displayName: 'GPT-4 Turbo', input: 10, output: 30, cacheRead: 0, cacheWrite: 0 },
    'gpt-4': { displayName: 'GPT-4', input: 30, output: 60, cacheRead: 0, cacheWrite: 0 },
    'gpt-3.5-turbo': { displayName: 'GPT-3.5 Turbo', input: 0.50, output: 1.50, cacheRead: 0, cacheWrite: 0 },

    // === Gemini Series ===
    'gemini-3.1-pro-preview': { displayName: 'Gemini 3.1 Pro Preview', input: 2, output: 12, cacheRead: 0.20, cacheWrite: 0 },
    'gemini-3.1-flash-lite-preview': { displayName: 'Gemini 3.1 Flash Lite Preview', input: 0.25, output: 1.50, cacheRead: 0.025, cacheWrite: 0 },
    'gemini-3-pro-preview': { displayName: 'Gemini 3 Pro Preview', input: 2, output: 12, cacheRead: 0.20, cacheWrite: 0 },
    'gemini-3-flash-preview': { displayName: 'Gemini 3 Flash Preview', input: 0.50, output: 3, cacheRead: 0.05, cacheWrite: 0 },

    // === Chinese Domestic Models ===
    'deepseek-v3.2': { displayName: 'DeepSeek V3.2', input: 2.00, output: 3.00, cacheRead: 0.200, cacheWrite: 0, currency: 'CNY' },
    'deepseek-v3.1': { displayName: 'DeepSeek V3.1', input: 4.00, output: 12.00, cacheRead: 0.400, cacheWrite: 0, currency: 'CNY' },
    'deepseek-v3': { displayName: 'DeepSeek V3', input: 2.00, output: 8.000, cacheRead: 0.200, cacheWrite: 0, currency: 'CNY' },
    'deepseek-chat': { displayName: 'DeepSeek Chat', input: 1.000, output: 2.000, cacheRead: 0.02, cacheWrite: 0, currency: 'CNY' },
    'deepseek-reasoner': { displayName: 'DeepSeek Reasoner', input: 1.000, output: 2.000, cacheRead: 0.02, cacheWrite: 0, currency: 'CNY' },
    'deepseek-r1': { displayName: 'DeepSeek R1', input: 1.000, output: 2.000, cacheRead: 0.02, cacheWrite: 0, currency: 'CNY' },
    'deepseek-v4-flash': { displayName: 'DeepSeek V4 Flash', input: 1.000, output: 2.000, cacheRead: 0.02, cacheWrite: 0, currency: 'CNY' },
    'deepseek-v4-flash-free': { displayName: 'DeepSeek V4 Flash Free', input: 0, output: 0, cacheRead: 0, cacheWrite: 0, currency: 'CNY' },
    'deepseek-v4-pro': { displayName: 'DeepSeek V4 Pro', input: 3, output: 6, cacheRead: 0.025, cacheWrite: 0, currency: 'CNY' },
    'kimi-k2-thinking': { displayName: 'Kimi K2 Thinking', input: 4.00, output: 16.00, cacheRead: 0.725, cacheWrite: 0, currency: 'CNY' },
    'kimi-k2-0905': { displayName: 'Kimi K2', input: 3.9875, output: 15.95, cacheRead: 0.725, cacheWrite: 0, currency: 'CNY' },
    'kimi-k2-turbo': { displayName: 'Kimi K2 Turbo', input: 8.0475, output: 58.435, cacheRead: 1.015, cacheWrite: 0, currency: 'CNY' },
    'kimi-k2.5': { displayName: 'Kimi K2.5', input: 4.00, output: 21.00, cacheRead: 0.70, cacheWrite: 0, currency: 'CNY' },
    'kimi-k2.6': { displayName: 'Kimi K2.6', input: 6.5, output: 27.00, cacheRead: 1.10, cacheWrite: 0, currency: 'CNY' },
    'kimi-k2.7-code': { displayName: 'Kimi K2.7 Code', input: 6.5, output: 27, cacheRead: 1.3, cacheWrite: 0, currency: 'CNY' },
    'kimi-k3': { displayName: 'Kimi K3', input: 20, output: 100, cacheRead: 2, cacheWrite: 0, currency: 'CNY' },
    'minimax-m2.1': { displayName: 'MiniMax M2.1', input: 2.1, output: 8.4, cacheRead: 0.21, cacheWrite: 2.625, currency: 'CNY' },
    'minimax-m2.1-lightning': { displayName: 'MiniMax M2.1 Lightning', input: 1.9575, output: 16.8925, cacheRead: 0.2175, cacheWrite: 0, currency: 'CNY' },
    'minimax-m2': { displayName: 'MiniMax M2', input: 1.9575, output: 6.8875, cacheRead: 0.2175, cacheWrite: 0, currency: 'CNY' },
    'minimax-m2.5': { displayName: 'MiniMax M2.5', input: 0.87, output: 6.8875, cacheRead: 0.2175, cacheWrite: 0, currency: 'CNY' },
    'minimax-m2.5-lightning': { displayName: 'MiniMax M2.5 Lightning', input: 2.175, output: 17.4, cacheRead: 0.2175, cacheWrite: 0, currency: 'CNY' },
    'minimax-m2.7': { displayName: 'MiniMax M2.7', input: 2.1, output: 8.4, cacheRead: 0.42, cacheWrite: 2.625, currency: 'CNY' },
    'minimax-m2.7-highspeed': { displayName: 'MiniMax M2.7 Highspeed', input: 4.2, output: 16.8, cacheRead: 0.42, cacheWrite: 2.625, currency: 'CNY' },
    'minimax-m3': { displayName: 'MiniMax M3', input: 4.2, output: 16.8, cacheRead: 0.84, cacheWrite: 0, currency: 'CNY' },
    'glm-4.5': { displayName: 'GLM-4.5', input: 2, output: 8, cacheRead: 0.2, cacheWrite: 0, currency: 'CNY' },
    'glm-4.5-air': { displayName: 'GLM-4.5 Air', input: 0.8, output: 2, cacheRead: 0.08, cacheWrite: 0, currency: 'CNY' },
    'glm-4.7': { displayName: 'GLM-4.7', input: 2, output: 8, cacheRead: 0.4, cacheWrite: 0, currency: 'CNY' },
    'glm-4.6': { displayName: 'GLM-4.6', input: 2, output: 8, cacheRead: 0.2, cacheWrite: 0, currency: 'CNY' },
    'glm-5': { displayName: 'GLM-5', input: 4, output: 18, cacheRead: 1, cacheWrite: 0, currency: 'CNY' },
    'glm-5.1': { displayName: 'GLM-5.1', input: 6, output: 24, cacheRead: 1.3, cacheWrite: 0, currency: 'CNY' },
    'glm-5.2': { displayName: 'GLM-5.2', input: 8, output: 28, cacheRead: 2, cacheWrite: 0, currency: 'CNY' },
    'mimo-v2.5-free': { displayName: 'MiMo V2.5 Flash Free', input: 0, output: 0, cacheRead: 0, cacheWrite: 0, currency: 'CNY' },
    'mimo-v2.5': { displayName: 'MiMo V2.5 Flash', input: 0.7, output: 2.1, cacheRead: 0.07, cacheWrite: 0, currency: 'CNY' },
    'mimo-v2.5-pro': { displayName: 'MiMo V2.5 Pro', input: 7, output: 21, cacheRead: 1.4, cacheWrite: 0, currency: 'CNY' },
    'qwen3.7-max': { displayName: 'Qwen3.7 Max', input: 6, output: 18, cacheRead: 0.6, cacheWrite: 7.5, currency: 'CNY' },
    'qwen3.7-plus': { displayName: 'Qwen3.7 Plus', input: 2, output: 8, cacheRead: 0.4, cacheWrite: 2.5, currency: 'CNY' },
    'qwen3.6-plus-free': { displayName: 'Qwen3.6 Plus Free', input: 0, output: 0, cacheRead: 0, cacheWrite: 0, currency: 'CNY' },
    'qwen3.6-plus': { displayName: 'Qwen3.6 Plus', input: 2, output: 12, cacheRead: 0.2, cacheWrite: 2.5, currency: 'CNY' },
    'qwen3.6-27b': { displayName: 'Qwen3.6 27B', input: 0, output: 0, cacheRead: 0, cacheWrite: 0, currency: 'CNY' },
    'qwen3.5-plus': { displayName: 'Qwen3.5 Plus', input: 0.8, output: 4.8, cacheRead: 0.08, cacheWrite: 1, currency: 'CNY' },
    'qwen3-coder-next': { displayName: 'Qwen3 Coder Next', input: 0.87, output: 5.4375, cacheRead: 0, cacheWrite: 0, currency: 'CNY' },

    // === Grok Series ===
    'grok-4.20-0309-reasoning': { displayName: 'Grok 4.20 Reasoning', input: 2, output: 6, cacheRead: 0.20, cacheWrite: 0 },
    'grok-4.20-0309-non-reasoning': { displayName: 'Grok 4.20', input: 2, output: 6, cacheRead: 0.20, cacheWrite: 0 },
    'grok-4-1-fast-reasoning': { displayName: 'Grok 4.1 Fast Reasoning', input: 0.20, output: 0.50, cacheRead: 0.05, cacheWrite: 0 },
    'grok-4-1-fast-non-reasoning': { displayName: 'Grok 4.1 Fast', input: 0.20, output: 0.50, cacheRead: 0.05, cacheWrite: 0 },
    'grok-4': { displayName: 'Grok 4', input: 3, output: 15, cacheRead: 0.75, cacheWrite: 0 },
    'grok-code-fast-1': { displayName: 'Grok Code Fast', input: 0.20, output: 1.50, cacheRead: 0.02, cacheWrite: 0 },
    'grok-3': { displayName: 'Grok 3', input: 3, output: 15, cacheRead: 0.75, cacheWrite: 0 },
    'grok-3-mini': { displayName: 'Grok 3 Mini', input: 0.25, output: 0.50, cacheRead: 0.075, cacheWrite: 0 },

    // === StepFun ===
    'step-3.5-flash': { displayName: 'Step 3.5 Flash', input: 0.10, output: 0.30, cacheRead: 0.02, cacheWrite: 0 },
};


export const MODEL_PRICING_ALIASES = {
    // Agent fallbacks and common short names
    'claude': 'claude-sonnet-4-20250514',
    'codex': 'gpt-5-codex',
    'gemini': 'gemini-3-pro-preview',
    'kimi': 'kimi-k2-0905',
    'qwen': 'qwen3.5-plus',

    // Claude aliases
    'claude-opus-4.7': 'claude-opus-4-7',
    'claude-opus-4-7-latest': 'claude-opus-4-7',
    'claude-opus-4.6': 'claude-opus-4-6-20260206',
    'claude-opus-4-6': 'claude-opus-4-6-20260206',
    'claude-sonnet-4.6': 'claude-sonnet-4-6-20260217',
    'claude-sonnet-4-6': 'claude-sonnet-4-6-20260217',
    'claude-opus-4.5': 'claude-opus-4-5-20251101',
    'claude-opus-4-5': 'claude-opus-4-5-20251101',
    'claude-sonnet-4.5': 'claude-sonnet-4-5-20250929',
    'claude-sonnet-4-5': 'claude-sonnet-4-5-20250929',
    'claude-haiku-4.5': 'claude-haiku-4-5-20251001',
    'claude-haiku-4-5': 'claude-haiku-4-5-20251001',
    'claude-opus-4.1': 'claude-opus-4-1-20250805',
    'claude-opus-4-1': 'claude-opus-4-1-20250805',
    'claude-opus-4-latest': 'claude-opus-4-7',
    'claude-opus-4': 'claude-opus-4-20250514',
    'claude-sonnet-4-latest': 'claude-sonnet-4-6-20260217',
    'claude-sonnet-4': 'claude-sonnet-4-20250514',

    // OpenAI / Codex aliases
    'gpt-5.6': 'gpt-5.6-sol',
    'gpt-5.6-latest': 'gpt-5.6-sol',
    'gpt-5.6-sol-latest': 'gpt-5.6-sol',
    'gpt-5.6-terra-latest': 'gpt-5.6-terra',
    'gpt-5.6-luna-latest': 'gpt-5.6-luna',
    'gpt-5.5-latest': 'gpt-5.5',
    'gpt-5.5-thinking': 'gpt-5.5',
    'gpt-5.4-latest': 'gpt-5.4',
    'gpt-5.2-latest': 'gpt-5.2',
    'gpt-5.2-codex-latest': 'gpt-5.2-codex',
    'gpt-5.3-codex-latest': 'gpt-5.3-codex',
    'gpt-5.1-latest': 'gpt-5.1',
    'gpt-5.1-codex-latest': 'gpt-5.1-codex',
    'gpt-5-codex-latest': 'gpt-5-codex',
    'gpt-5-chat-latest': 'gpt-5-chat',
    'gpt-5-latest': 'gpt-5',
    'gpt-5-mini-latest': 'gpt-5-mini',
    'gpt-5-nano-latest': 'gpt-5-nano',
    'codex-mini-latest': 'codex-mini',
    'o3-latest': 'o3',
    'o3-mini-latest': 'o3-mini',
    'o3-pro-latest': 'o3-pro',
    'o4-mini-latest': 'o4-mini',
    'o1-preview-latest': 'o1-preview',
    'o1-mini-latest': 'o1-mini',
    'gpt-4.1-latest': 'gpt-4.1',
    'gpt-4.1-mini-latest': 'gpt-4.1-mini',
    'gpt-4.1-nano-latest': 'gpt-4.1-nano',
    'chatgpt-4o-latest': 'gpt-4o',
    'gpt-4o-latest': 'gpt-4o',
    'gpt-4o-2024-08-06': 'gpt-4o',
    'gpt-4o-2024-11-20': 'gpt-4o',
    'gpt-4o-mini-2024-07-18': 'gpt-4o-mini',
    'gpt-4-turbo-preview': 'gpt-4-turbo',
    'gpt-4-0125-preview': 'gpt-4-turbo',
    'gpt-4-1106-preview': 'gpt-4-turbo',
    'gpt-4-0613': 'gpt-4',
    'gpt-3.5-turbo-0125': 'gpt-3.5-turbo',
    'gpt-3.5-turbo-1106': 'gpt-3.5-turbo',

    // Gemini aliases
    'gemini-3.1-pro': 'gemini-3.1-pro-preview',
    'gemini-3.1-flash-lite': 'gemini-3.1-flash-lite-preview',
    'gemini-3-pro': 'gemini-3-pro-preview',
    'gemini-3-flash': 'gemini-3-flash-preview',

    // Domestic provider aliases
    'deepseek-v3-0324': 'deepseek-v3',
    'deepseek-chat-v3-0324': 'deepseek-v3',
    'deepseek-v3.1-terminus': 'deepseek-v3.1',
    'deepseek-v3.2-exp': 'deepseek-v3.2',
    'deepseek-r1-0528': 'deepseek-r1',
    'deepseek-r1-distill-qwen-32b': 'qwen3.5-plus',
    'deepseek-r1-distill-llama-70b': 'deepseek-r1',
    'deepseekv4flashfree': 'deepseek-v4-flash-free',
    'deepseekv4flash': 'deepseek-v4-flash',
    'deepseekv4pro': 'deepseek-v4-pro',
    'kimi-k2': 'kimi-k2-0905',
    'kimi-k2-latest': 'kimi-k2-0905',
    'kimi-k2-0711-preview': 'kimi-k2-0905',
    'kimi-k2-instruct': 'kimi-k2-0905',
    'kimi-k2-thinking-latest': 'kimi-k2-thinking',
    'moonshot-kimi-k2': 'kimi-k2-0905',
    'moonshot-kimi-k2-thinking': 'kimi-k2-thinking',
    'minimax-m2-latest': 'minimax-m2',
    'minimax-m2.1-latest': 'minimax-m2.1',
    'minimax-m2.1-lightning-latest': 'minimax-m2.1-lightning',
    'minimax-m2.5-latest': 'minimax-m2.5',
    'minimax-m2.5-lightning-latest': 'minimax-m2.5-lightning',
    'minimax-m2.7-latest': 'minimax-m2.7',
    'minimax-m2.7-highspeed-latest': 'minimax-m2.7-highspeed',
    'glm-4.5v': 'glm-4.5',
    'glm-4.5-airx': 'glm-4.5-air',
    'glm-4-plus': 'glm-4.5',
    'glm-4-air': 'glm-4.5-air',
    'glm-4.6-latest': 'glm-4.6',
    'glm-4.7-latest': 'glm-4.7',
    'glm-5-latest': 'glm-5',
    'glm-5.1-latest': 'glm-5.1',
    'glm-5.2-promo': 'glm-5.2',
    'qwen-plus': 'qwen3.5-plus',
    'qwen-plus-latest': 'qwen3.5-plus',
    'qwen-turbo': 'qwen3.5-plus',
    'qwen-long': 'qwen3.5-plus',
    'qwen3-next-80b-a3b-instruct': 'qwen3-coder-next',
    'qwen3-next-80b-a3b-thinking': 'qwen3-coder-next',

    // xAI aliases
    'grok-4-latest': 'grok-4',
    'grok-4-fast-reasoning': 'grok-4-1-fast-reasoning',
    'grok-4-fast-non-reasoning': 'grok-4-1-fast-non-reasoning',
    'grok-3-latest': 'grok-3',
    'grok-3-mini-latest': 'grok-3-mini',
    'grok-3-mini-fast': 'grok-3-mini',
    'grok-code-fast': 'grok-code-fast-1',
};

export const CACHE_INCLUSIVE_APP_TYPES = new Set(['codex', 'gemini', 'qwen', 'zcode']);

const PROVIDER_PREFIXES = [
    ['claude', 'Anthropic'],
    ['gpt', 'OpenAI'],
    ['o1', 'OpenAI'],
    ['o3', 'OpenAI'],
    ['o4', 'OpenAI'],
    ['codex-mini', 'OpenAI'],
    ['gemini', 'Google'],
    ['deepseek', 'DeepSeek'],
    ['kimi', 'Moonshot'],
    ['minimax', 'MiniMax'],
    ['glm', 'Zhipu'],
    ['mimo', 'Xiaomi'],
    ['qwen', 'Alibaba'],
    ['qwq', 'Alibaba'],
    ['grok', 'xAI'],
    ['step', 'StepFun'],
];

export function getProviderName(modelId) {
    const lower = modelId.toLowerCase();
    for (const [prefix, name] of PROVIDER_PREFIXES) {
        if (lower.startsWith(prefix))
            return name;
    }
    return '其他';
}

export const SUPPORTED_AGENTS = [
    { id: 'claude', name: 'Claude Code' },
    { id: 'codex', name: 'Codex (OpenAI)' },
    { id: 'gemini', name: 'Gemini CLI' },
    { id: 'kiro', name: 'Kiro CLI' },
    { id: 'opencode', name: 'OpenCode' },
    { id: 'amp', name: 'Amp' },
    { id: 'codebuff', name: 'Codebuff' },
    { id: 'hermes', name: 'Hermes Agent' },
    { id: 'pi', name: 'Pi Agent' },
    { id: 'goose', name: 'Goose' },
    { id: 'openclaw', name: 'OpenClaw' },
    { id: 'kilo', name: 'Kilo' },
    { id: 'kimi', name: 'Kimi Code' },
    { id: 'qwen', name: 'Qwen' },
    { id: 'copilot', name: 'GitHub Copilot CLI' },
    { id: 'zcode', name: 'ZCode' },
];

export const AGENT_DISPLAY_NAMES = {
    claude: 'Claude Code',
    codex: 'Codex',
    gemini: 'Gemini CLI',
    kiro: 'Kiro CLI',
    opencode: 'OpenCode',
    amp: 'Amp',
    codebuff: 'Codebuff',
    hermes: 'Hermes Agent',
    pi: 'Pi Agent',
    goose: 'Goose',
    openclaw: 'OpenClaw',
    kilo: 'Kilo',
    kimi: 'Kimi Code',
    qwen: 'Qwen',
    copilot: 'Copilot CLI',
    zcode: 'ZCode',
};

export const AGENT_BRAND_COLORS = {
    claude: '#D97757',
    codex: '#10A37F',
    gemini: '#4285F4',
    kiro: '#7C3AED',
    opencode: '#1a1818',
    amp: '#A112FF',
    codebuff: '#22C55E',
    hermes: '#E5A50A',
    pi: '#00AAFF',
    goose: '#F97316',
    openclaw: '#FF4136',
    kilo: '#3B82F6',
    kimi: '#000000',
    qwen: '#4a94e3',
    copilot: '#8534F3',
    zcode: '#2563EB',
};

export const AGENT_BRAND_TEXT_COLORS = {
    opencode: '#ebebeb',
};

export const AGENT_APP_TYPE_MAP = {
    claude: 'claude',
    codex: 'codex',
    gemini: 'gemini',
    kiro: 'kiro',
    opencode: 'opencode',
    amp: 'amp',
    codebuff: 'codebuff',
    hermes: 'hermes',
    pi: 'pi',
    goose: 'goose',
    openclaw: 'openclaw',
    kilo: 'kilo',
    kimi: 'kimi',
    qwen: 'qwen',
    copilot: 'copilot',
    zcode: 'zcode',
};
